### ISSUE TITLE
bin executable for a11y-tests-web

### ISSUE THREAD

**Issue by radiocontrolled** [bbc/a11y-tests-web#20]
It would be good to be able to install a11y-tests-web as a node script from npm.

**Comment by andymsuk** [comment]
I think this is something @jennyrobertsonbbc is after too now 😃 

If anyone's got time to submit a PR, that'd be great!

**Comment by andymsuk** [comment]
@jennyrobertsonbbc and I are now actively working on this!

**Comment by andymsuk** [comment]
Added as a new feature under https://github.com/bbc/a11y-tests-web/pull/35
